package com.mundolimpio.migration;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test de verificación de sintaxis PostgreSQL en migraciones Flyway.
 *
 * QUE HACE: Escanea los archivos SQL de migración y verifica que no contengan
 * sintaxis MySQL exclusiva (AUTO_INCREMENT, ENGINE=InnoDB, etc.).
 *
 * POR QUE: Al migrar de MySQL a PostgreSQL, necesitamos asegurar que todas
 * las migraciones V1-V4 usen sintaxis compatible con PostgreSQL antes de
 * ejecutarlas contra la base de datos real.
 *
 * DIFERENCIA con un test de integración con Testcontainers:
 * - Este test es ESTRUCTURAL: solo revisa el texto de los archivos .sql
 * - No necesita conexión a base de datos — se ejecuta en milisegundos
 * - Los tests con Testcontainers (PR 1.2) verificarán que las migraciones
 *   realmente CORREN contra PostgreSQL
 */
class FlywayMigrationSyntaxTest {

    private static final String MIGRATIONS_DIR = "src/main/resources/db/migration";

    /**
     * Verifica que ninguna migración V1-V4 contenga sintaxis MySQL
     * excluida como AUTO_INCREMENT o ENGINE=InnoDB.
     *
     * RED: Este test falla ANTES de reescribir las migraciones porque
     * V1 y V2 contienen AUTO_INCREMENT.
     * GREEN: Pasa DESPUÉS de reemplazar AUTO_INCREMENT por
     * GENERATED BY DEFAULT AS IDENTITY.
     */
    @Test
    void allMigrationsMustNotContainMySqlOnlySyntax() throws IOException {
        Path migrationsPath = Paths.get(MIGRATIONS_DIR).toAbsolutePath();
        assertTrue(Files.isDirectory(migrationsPath),
                "El directorio de migraciones debe existir: " + migrationsPath);

        List<Path> sqlFiles = Files.list(migrationsPath)
                .filter(p -> p.toString().endsWith(".sql")
                        && !p.toString().endsWith(".bak"))
                .collect(Collectors.toList());

        assertFalse(sqlFiles.isEmpty(), "Debe haber al menos un archivo .sql de migración");

        for (Path sqlFile : sqlFiles) {
            String content = Files.readString(sqlFile).toUpperCase();
            String filename = sqlFile.getFileName().toString();

            // Verificar que NO contenga sintaxis MySQL
            assertFalse(content.contains("AUTO_INCREMENT"),
                    filename + " no debe contener AUTO_INCREMENT (usar GENERATED ... AS IDENTITY en su lugar)");
            assertFalse(content.contains("ENGINE=INNODB"),
                    filename + " no debe contener ENGINE=InnoDB");
        }
    }

    /**
     * Verifica que las migraciones V1-V4 usen GENERATED BY DEFAULT AS IDENTITY
     * para las columnas de clave primaria (PostgreSQL-compatible).
     */
    @Test
    void identityColumnsMustUsePostgreSqlSyntax() throws IOException {
        Path migrationsPath = Paths.get(MIGRATIONS_DIR).toAbsolutePath();
        List<Path> sqlFiles = Files.list(migrationsPath)
                .filter(p -> p.toString().endsWith(".sql")
                        && !p.toString().endsWith(".bak"))
                .sorted()
                .collect(Collectors.toList());

        for (Path sqlFile : sqlFiles) {
            String content = Files.readString(sqlFile);
            String filename = sqlFile.getFileName().toString();

            // Si el archivo tiene CREATE TABLE con PRIMARY KEY, debe usar IDENTITY
            if (content.toUpperCase().contains("CREATE TABLE")) {
                assertTrue(content.contains("GENERATED BY DEFAULT AS IDENTITY"),
                        filename + " debe usar GENERATED BY DEFAULT AS IDENTITY para PKs");
            }
        }
    }

    /**
     * Verifica que los archivos .bak originales existan y contengan
     * la sintaxis MySQL original (AUTO_INCREMENT).
     */
    @Test
    void originalMySqlMigrationsMustBeArchived() throws IOException {
        Path migrationsPath = Paths.get(MIGRATIONS_DIR).toAbsolutePath();
        List<Path> bakFiles = Files.list(migrationsPath)
                .filter(p -> p.toString().endsWith(".sql.bak"))
                .collect(Collectors.toList());

        assertEquals(4, bakFiles.size(),
                "Deben existir 4 archivos .bak (V1-V4)");
    }
}
