-- V5__Create_Purchase_Tables.sql
-- WHAT: Crea las tablas suppliers, purchases y purchase_items para el módulo receipt (compras).
-- WHY: No existía concepto de compras — solo ventas (outgoing). Necesitamos registrar
--      compras de materia prima con imágenes de tickets digitalizadas vía OCR.
-- DIFFERENCES: Las compras tienen supplier (proveedor) y admin (quién registró),
--              a diferencia de sales que solo registran el monto total y fecha.

CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(500) NOT NULL,
    supplier_id BIGINT NOT NULL,
    admin_id BIGINT NOT NULL,
    purchase_date DATE NOT NULL,
    total DECIMAL(19,4) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version BIGINT DEFAULT 0,
    CONSTRAINT fk_purchase_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_admin FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(19,4) NOT NULL,
    total_price DECIMAL(19,4) NOT NULL,
    bulk_product_id BIGINT,
    CONSTRAINT fk_item_purchase FOREIGN KEY (purchase_id) REFERENCES purchases(id) ON DELETE CASCADE,
    CONSTRAINT fk_item_bulk_product FOREIGN KEY (bulk_product_id) REFERENCES bulk_products(id) ON DELETE SET NULL
);

-- Índice para búsqueda de proveedores por nombre (usado en findOrCreate del servicio)
CREATE INDEX idx_supplier_name ON suppliers(name);
