-- V9__Add_Audit_Log.sql
-- WHAT: Crea la tabla audit_log para registrar cambios de datos sensibles
--        (cambios de rol, ajustes de stock, eliminacion de productos,
--        confirmacion de recibos, ejecucion de produccion).
-- WHY: UR-R7 requiere que cambios de rol y otras operaciones administrativas
--      queden registradas para trazabilidad y compliance. La tabla usa
--      actor_id (FK a users) para identificar quien realizo el cambio,
--      old_value/new_value TEXT para flexibilidad con diferentes tipos de datos,
--      y entity_type/entity_id para identificar el recurso afectado.
-- DIFFERENCES: Es una tabla nueva, no reemplaza nada existente. El servicio
--              AuditLogService escribira aqui via @Async + REQUIRES_NEW para
--              no bloquear la operacion principal y sobrevivir rollbacks.

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id VARCHAR(50),
    action VARCHAR(50) NOT NULL,
    field_name VARCHAR(100),
    old_value TEXT,
    new_value TEXT,
    performed_by BIGINT NOT NULL,
    performed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45),
    notes TEXT,
    CONSTRAINT fk_audit_log_performer FOREIGN KEY (performed_by)
        REFERENCES users(id) ON DELETE RESTRICT
);

-- Indice compuesto para busquedas por entidad (ej: todos los cambios de un usuario)
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log(entity_type, entity_id);

-- Indice para buscar todas las acciones realizadas por un usuario
CREATE INDEX IF NOT EXISTS idx_audit_performer ON audit_log(performed_by);
